### ISSUE TITLE
Live search

### ISSUE THREAD

**Issue by meat147** [meat147/Point-of-Sale#6]
There is to ways to implement this: 

Clientside:
pass all customers, orders and products to the client (wich will create a lot of traffic but for me the easier way right now)
or 
serverside: request live (ajax?) data from the backend

**Comment by TrueFiction** [comment]
**My Views on the 2 Suggested Options**
( All of this is said as a naive web developer who is fairly unfamiliar with Node.js )
By the way, I came across these links and they may be helpful for your issue generally:
http://stackoverflow.com/questions/29120971/ajax-live-search-with-node-js 

**Client-side:** 
Pass all customers, orders, and products to each individual client is a poor design choice if the data is not secure which it may not be if the Hypertext Transfer Protocol Secure (https) is not enforced (no SSL/TLS, opening vulnerabilities). Nevertheless if you can send only the respective user's data at load time this can be desirable because it allows for caching of any data on the slow load which will happen anyways.  

**Server-side:** 
Asynchronous JavaScript and XML request is the way to go, it is very quick and essentially immediate, the best of these two options when considering speed in all cases. This may be helpful:
https://github.com/caolan/async 

**Another Solution?** 
I have not yet run the application and also do not have a knowledge of the back-end besides the model files and the fact that some variant of MongoDB is being used. In spite of my lack of specific knowledge, you might consider having a background worker (JavaScript job) running on the back-end server if you have that capability; this worker will slowly (assuming free-tier or low-cost server is the back-end) make database calls and send the database payload to your web page via a HTTPS POST call after loading all the data which will be handled by a local script on the front-end. These may be helpful: 
http://www.html5rocks.com/en/tutorials/workers/basics/
https://github.com/scttnlsn/monq

**Data-Binding**
One last thing, implementing data-binding is an option for later down the line _**if it has not been done already**_, since there are numerous libraries on npm for the data-binding. However, this would likely require modification of both back-end and front-end, with more total time spent on the back-end implementation. This may be helpful:
https://www.npmjs.com/package/mongoskin

I've seen many live searches implemented before and I'm confident that you will be able to solve this if you take the time to implement this feature. Good luck on your issue! 

_**Ryan Milkovits**_

**Comment by meat147** [comment]
Hello Ryan Milkovits,

thanks for your feedback i switched to an API end point and front end rendering of the tables. Customers already works amazing good with this. 

https://github.com/meat147/Point-of-Sale/blob/master/routes/api/customers.js#L12
The Customer endpoint has 2 get params one for an search and one for pagination.


Best Regards Pierre

**Comment by meat147** [comment]
Live search is now here with React on Products and with Pure Javascript on Customers.
